/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:61099d5e309dd5126895cb2d006c93a6:7979479a5ba52a9c36728fb50f2150eb:c698189650b7189882f78ad41920bb28$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class WalkAnim
	{
		public const string WalkAnim_0001 = "0001";
		public const string WalkAnim_0002 = "0002";
		public const string WalkAnim_0003 = "0003";
		public const string WalkAnim_0004 = "0004";
		public const string WalkAnim_0005 = "0005";
		public const string WalkAnim_0006 = "0006";
		public const string WalkAnim_0007 = "0007";
		public const string WalkAnim_0008 = "0008";
		public const string WalkAnim_0009 = "0009";
		public const string WalkAnim_0010 = "0010";
		public const string WalkAnim_0011 = "0011";
		public const string WalkAnim_0012 = "0012";
		public const string WalkAnim_0013 = "0013";
		public const string WalkAnim_0014 = "0014";
		public const string WalkAnim_0015 = "0015";
		public const string WalkAnim_0016 = "0016";
	}
}