/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:66cd11f546353c077071782e99fd782c:804b3aaf6dbae1709cd4f8214dcfcfcc:307d41d1ade8cc6c66b824d21097c216$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class Ricochet
	{
		public const string Ricochet1 = "ricochet1";
		public const string Ricochet2 = "ricochet2";
		public const string Ricochet3 = "ricochet3";
		public const string Ricochet4 = "ricochet4";
	}
}